# ------------------
# Zithium Core
# ------------------

# Enable or disable certain modules here.
Modules:
  # Should we enable the player-listener module
  player-listener: false

  # Should we enable the auto announcer module
  auto-announcer: false

  # Should we enable the chat formatting module
  chat-format: true

  # Should we enable the custom commands module
  custom-commands: false

  # Should we enable the auto trash module
  auto-trash: false

  # Should we enable the chat filter module
  chat-filter: true

  # Should we automatically clear dropped items & entities? REQUIRES RoseStacker
  entity-clear: true

# Settings related to the automatic entity clear. # REQUIRES RoseStacker
entity-clearing:

  # Should we clear stacked items that are dropped on the ground?
  clear-items: true

  # Should we clear stacked entities?
  clear-entities: true

  # How often the clear task runs
  delay: 120 # in seconds

# Settings relating to Players. To enable change "player-listener" to true.
Players:
  # Should we disable default join messages?
  disable-join-messages: false

  # Should we disable default quit messages?
  disable-quit-messages: false

  # Should we use the custom messages below?
  use-custom-join-quit-message: true

  # Custom messages if above option is set to true
  custom-messages:
    # Custom Join Message sent when a user joins and the above setting is set to true.
    join-message: "<green>%player% has joined the server."

    # Custom Quit Message sent when a user leaves and the above setting is set to true.
    quit-message: "<red>%player% has left the server."


Auto-Announcer:
  # The delay between announcements. (In Seconds)
  delay: 800

  # Create your very own announcements here
  announcements:
    test1:
      - "<reset>"
      - "<aqua>This is an example announcement <gray>(#1)"
      - "<reset>"
    test2:
      - "&r"
      - "<red>This is an example announcement <gray>(#2)"
      - "&r"


# Settings for the chat filter. Add any words here to be blocked.
Chat-Filter:
  blocked-words:
    - fuck
    - shit

# Message for the /donation command
Donation-Announcement:
  - '{player} has donated GG!'

# Chat formatting Placeholders:
# The content of the message is added at the end.
Chat-Formats:
  default: "%kyorify_luckperms_prefix%%kyorify_player_name%:<reset> "

  # Set the format per group. Format is based on the name of their primary group.
  group-formats:
  #  default: "[Default] %kyorify_player_name%: "
  #  admin: "[Admin] %kyorify_player_name%: "


# Custom Commands
Custom-Commands:
  #This is the command name. This command for example is /twitter.
  twitter:
    #The message sent when the user runs the commands. Supports PlaceholderAPI
    message:
      - "<yellow><bold>[!] TWITTER</bold>"
      - "<gold><bold>*</bold> <white>Follow us on twitter <yellow>@ItzSave"