name: 'ZithiumCore'
version: '${version}'
main: net.zithium.core.ZithiumCore
api-version: '1.19'
authors: [ Save ]
dependencies:
  - name: LuckPerms
    required: false
  - name: PlaceholderAPI
    required: false
  - name: RoseStacker
    required: false

load-after:
  - name: RoseStacker
    bootstrap: false

permissions:
  zcore.admin:
    description: Allows the user to reload the plugin
    default: op
    children:
      - zcore.command.reload
      - zcore.command.info
      - zcore.command.autotrash
  zcore.command.info:
    description: Allows the user to use the information command.
    default: op
  zcore.command.reload:
    description: Allows the user to use the reload command.
    default: op
  zcore.command.autotrash:
    description: Allows access to the auto trash command.
    default: op