name: 'SaveCore'
version: '${version}'
main: org.itzsave.SaveCore
api-version: 1.19
authors: [ Save ]
dependencies:
  - name: LuckPerms
    required: false
  - name: PlaceholderAPI
    required: false
permissions:
  savecore.admin:
    description: Allows the user to reload the plugin
    default: op
    children:
      - savecore.command.reload
      - savecore.command.info
  savecore.command.info:
    description: Allows the user to use the information command.
    default: op